spring:
    application:
        name: gateway
    redis:
        database: 8
        host: 192.168.3.8
        port: 6379
        pool:
          #连接池支持的最大连接数
          max-active: 600
          #连接池中连接用完时,新的请求等待时间,毫秒
          max-wait: 10000
          #连接池中最多可空闲maxIdle个连接
          max-idle: 300

server:
    port: 8762 #启动端口
    compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain
      min-response-size: 2048

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
